os: Ubuntu2004
platform:
  - x64
install:
  - sudo apt update && sudo apt install --allow-unauthenticated -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils ruby-dev libvirt-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
  - sudo dpkg -i vagrant_2.2.14_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule update --init --recursive
build_script:
  - cp -v salt/roots/pillar/podman.sls.example salt/roots/pillar/podman.sls
  - cp -v salt/roots/pillar/opendj.sls.example salt/roots/pillar/opendj.sls
  - cp -v vagrant/examples/Vagrantfile.opendj-box.fedora-34.x86_64.example vagrant/Vagrantfile.opendj-box
  - sudo vagrant up --provider=libvirt opendj-box
  - sudo vagrant ssh opendj-box -- sudo salt-call state.highstate
  - sudo vagrant ssh opendj-box -- sudo salt-call state.sls opendj
  - sudo vagrant destroy --force opendj-box
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
